// The 9 Unresolved Rules under QĐ 525/QĐ-THPT.VTT
// These rules must be explicitly confirmed by GVCN before taking any official score effect.
// Category: UNRESOLVED RULE — REQUIRES GVCN CONFIRMATION

import { PendingRule } from '../../types';

export const OFFICIAL_PENDING_RULES: PendingRule[] = [
  {
    code: 'PENDING-01',
    title: 'Xung đột thang điểm trừ và quy tắc tái phạm (Mã 01–18)',
    ambiguity: 'Bảng điểm mục II quy định điểm trừ theo mã (01-12: -2; 13-15: -4; 16-18: -6). Tuy nhiên mục III.5 lại ghi: lỗi 01-18 lần 1 và 2 trừ 2 điểm, lần 3 trở đi nhân đôi, nhân ba theo số lần vi phạm.',
    source_reference: 'QĐ 525 Mục II.2 vs Mục III.5',
    options: [
      {
        id: 'opt1_table_fixed',
        label: 'Áp dụng theo bảng điểm cố định mục II (01-12: -2; 13-15: -4; 16-18: -6)',
        description: 'Mỗi lần vi phạm trừ đúng điểm ghi trong bảng danh mục',
      },
      {
        id: 'opt2_progressive_section_iii',
        label: 'Áp dụng quy tắc lũy tiến mục III.5 (Lần 1,2: -2; Lần 3+: nhân đôi/ba)',
        description: 'Coi quy định mục III.5 là quy tắc điều chỉnh lũy tiến',
      },
      {
        id: 'opt3_hybrid_wait',
        label: 'Tạm giữ nguyên điểm bảng mục II, chờ hướng dẫn chính thức bằng văn bản từ BGH',
        description: 'Không nhân lũy tiến khi chưa có hướng dẫn bằng văn bản',
      },
    ],
    selected_option: 'opt1_table_fixed',
    basis: 'Phê duyệt trực tiếp theo phương án đã chọn (GVCN & Ban Cán Sự Lớp 10A16)',
    effective_from: '2026-09-01',
    effective_to: '2027-06-30',
    status: 'confirmed_by_gvcn',
    configured_by: 'Thầy Trần Duy Tân (GVCN)',
    confirmed_by: 'Thầy Trần Duy Tân (GVCN)',
  },
  {
    code: 'PENDING-02',
    title: 'Phạm vi tính số lần tái phạm',
    ambiguity: 'Văn bản nguồn không nêu rõ số lần vi phạm được đếm theo từng mã lỗi cụ thể, theo nhóm hành vi, hay tính theo phạm vi Tuần, Tháng, Học kỳ, hay Cả năm học.',
    source_reference: 'QĐ 525 Mục III.5',
    options: [
      { id: 'opt_scope_code_week', label: 'Theo từng mã lỗi cụ thể trong phạm vi Tuần', description: 'Đặt lại số lần vi phạm vào đầu mỗi tuần' },
      { id: 'opt_scope_code_month', label: 'Theo từng mã lỗi cụ thể trong phạm vi Tháng', description: 'Đặt lại số lần vi phạm vào đầu mỗi tháng' },
      { id: 'opt_scope_code_semester', label: 'Theo từng mã lỗi cụ thể trong phạm vi Học kỳ', description: 'Tính lũy kế xuyên suốt học kỳ' },
    ],
    selected_option: 'opt_scope_code_week',
    basis: 'Phê duyệt trực tiếp theo phương án đã chọn (GVCN & Ban Cán Sự Lớp 10A16)',
    effective_from: '2026-09-01',
    effective_to: '2027-06-30',
    status: 'confirmed_by_gvcn',
    configured_by: 'Thầy Trần Duy Tân (GVCN)',
    confirmed_by: 'Thầy Trần Duy Tân (GVCN)',
  },
  {
    code: 'PENDING-03',
    title: 'Thời điểm và cơ chế ghi nhận điểm thưởng RW03 (Cán bộ lớp/Đoàn)',
    ambiguity: 'Mục II.1 ghi "+1 điểm/tháng", nhưng ngoặc đơn ghi: "chủ nhiệm đánh giá bằng văn bản vào cuối học kỳ". Chưa rõ điểm này cộng vào từng tháng hay dồn vào cuối kỳ.',
    source_reference: 'QĐ 525 Mục II.1 (RW03)',
    options: [
      { id: 'opt_rw03_end_of_semester', label: 'Cộng dồn vào điểm tổng kết học kỳ sau khi có văn bản đánh giá', description: 'Cuối kỳ GVCN đánh giá và cộng một lần' },
      { id: 'opt_rw03_retroactive_monthly', label: 'Truy lĩnh chia đều vào điểm các tháng trong học kỳ', description: 'Cập nhật lại snapshot các tháng trước đó' },
      { id: 'opt_rw03_monthly_advance', label: 'Tạm ứng cộng từng tháng và hủy nếu cuối kỳ không đạt xuất sắc', description: 'Ghi nhận hàng tháng có điều kiện' },
    ],
    selected_option: 'opt_rw03_end_of_semester',
    basis: 'Phê duyệt trực tiếp theo phương án đã chọn (GVCN & Ban Cán Sự Lớp 10A16)',
    effective_from: '2026-09-01',
    effective_to: '2027-06-30',
    status: 'confirmed_by_gvcn',
    configured_by: 'Thầy Trần Duy Tân (GVCN)',
    confirmed_by: 'Thầy Trần Duy Tân (GVCN)',
  },
  {
    code: 'PENDING-04',
    title: 'Quy tắc làm tròn số thập phân, tuần chuyển tháng và tuần lễ/ngắn',
    ambiguity: 'Nguồn không nêu quy tắc làm tròn (ví dụ: 6.95 có được làm tròn thành 7.0 để đạt Tốt hay không); chưa có hướng dẫn phân bổ tuần vắt giữa 2 tháng hoặc tuần nghỉ lễ.',
    source_reference: 'QĐ 525 Mục III (Thang điểm và xếp loại)',
    options: [
      { id: 'opt_round_none', label: 'Không làm tròn, giữ nguyên số thực (>= 7.00 mới đạt Tốt, 6.95 xếp Khá)', description: 'Chính xác tuyệt đối theo ngưỡng toán học' },
      { id: 'opt_round_standard_1dec', label: 'Làm tròn tiêu chuẩn 1 chữ số thập phân (6.95 -> 7.0)', description: 'Theo thông lệ làm tròn học bạ' },
      { id: 'opt_round_gvcn_decision', label: 'Để GVCN xem xét linh hoạt trong phiên họp đánh giá học kỳ', description: 'Không tự động làm tròn bằng phần mềm' },
    ],
    selected_option: 'opt_round_standard_1dec',
    basis: 'Phê duyệt trực tiếp theo phương án đã chọn (GVCN & Ban Cán Sự Lớp 10A16)',
    effective_from: '2026-09-01',
    effective_to: '2027-06-30',
    status: 'confirmed_by_gvcn',
    configured_by: 'Thầy Trần Duy Tân (GVCN)',
    confirmed_by: 'Thầy Trần Duy Tân (GVCN)',
  },
  {
    code: 'PENDING-05',
    title: 'Quy đổi ngưỡng cảnh báo nghỉ quá 45 buổi học',
    ambiguity: 'Văn bản nêu quy định nghỉ quá 45 buổi theo kế hoạch 01 buổi/ngày (Chương trình GDPT), trong khi trường thực tế học 2 buổi/ngày (sáng + chiều).',
    source_reference: 'QĐ 525 Mục B.3 trang 5',
    options: [
      { id: 'opt_45_days_calendar', label: 'Đếm theo ngày nghỉ thực tế (1 ngày nghỉ cả 2 buổi tính là 1 đơn vị)', description: 'Bảo đảm quyền lợi học sinh theo tinh thần Chương trình GDPT' },
      { id: 'opt_45_sessions_half', label: 'Quy đổi 2 buổi = 1 ngày nghỉ (ngưỡng 90 buổi trường)', description: 'Chia đôi tổng số buổi nghỉ trên hệ thống' },
      { id: 'opt_45_strict_warning', label: 'Chỉ phát cảnh báo riêng biệt, tuyệt đối không tự động quyết định lưu ban', description: 'Yêu cầu GVCN đối chiếu sổ bộ trường' },
    ],
    selected_option: 'opt_45_days_calendar',
    basis: 'Phê duyệt trực tiếp theo phương án đã chọn (GVCN & Ban Cán Sự Lớp 10A16)',
    effective_from: '2026-09-01',
    effective_to: '2027-06-30',
    status: 'confirmed_by_gvcn',
    configured_by: 'Thầy Trần Duy Tân (GVCN)',
    confirmed_by: 'Thầy Trần Duy Tân (GVCN)',
  },
  {
    code: 'PENDING-06',
    title: 'Phạm vi đếm và điểm trừ lỗi sử dụng điện thoại (Mã 24)',
    ambiguity: 'Mục III.6 quy định: lần 1 trừ 6 điểm, lần 2 trần Đạt, lần 3 Chưa đạt. Chưa xác định phạm vi đếm (tuần/tháng/kỳ) và điểm số bị trừ ở lần 2, lần 3 có kèm trừ 6 điểm nữa hay không.',
    source_reference: 'QĐ 525 Mục III.6',
    options: [
      { id: 'opt_phone_sem_cap_only', label: 'Lần 2, 3 chỉ khống chế xếp loại học kỳ, không trừ thêm điểm tuần', description: 'Chỉ áp trần Đạt / Chưa đạt' },
      { id: 'opt_phone_deduct_and_cap', label: 'Mỗi lần đều trừ 6 điểm tuần và đồng thời áp trần học kỳ', description: 'Vừa trừ điểm tuần vừa áp trần kỳ' },
    ],
    selected_option: 'opt_phone_sem_cap_only',
    basis: 'Phê duyệt trực tiếp theo phương án đã chọn (GVCN & Ban Cán Sự Lớp 10A16)',
    effective_from: '2026-09-01',
    effective_to: '2027-06-30',
    status: 'confirmed_by_gvcn',
    configured_by: 'Thầy Trần Duy Tân (GVCN)',
    confirmed_by: 'Thầy Trần Duy Tân (GVCN)',
  },
  {
    code: 'PENDING-07',
    title: 'Xử lý hành vi "Làm việc riêng" trong giờ học (Mã 06)',
    ambiguity: 'Bảng mã mục II.2 mã 06 ghi "học môn khác", nhưng mục B.4 trang 5 nêu thêm "không làm việc riêng". Cần làm rõ "làm việc riêng" có thuộc mã 06 hay không.',
    source_reference: 'QĐ 525 Mục II.2 mã 06 vs Mục B.4 trang 5',
    options: [
      { id: 'opt_v06_include_private_work', label: 'Quy về mã 06 (Ngồi không đúng sơ đồ, ngủ, làm việc riêng/môn khác)', description: 'Gộp vào mã 06 (-2 điểm)' },
      { id: 'opt_v06_separate_safety', label: 'Tạm xếp vào "Sự việc khác — chờ xem xét", yêu cầu GVCN xác định', description: 'Không tự động map vào mã 06' },
    ],
    selected_option: 'opt_v06_include_private_work',
    basis: 'Phê duyệt trực tiếp theo phương án đã chọn (GVCN & Ban Cán Sự Lớp 10A16)',
    effective_from: '2026-09-01',
    effective_to: '2027-06-30',
    status: 'confirmed_by_gvcn',
    configured_by: 'Thầy Trần Duy Tân (GVCN)',
    confirmed_by: 'Thầy Trần Duy Tân (GVCN)',
  },
  {
    code: 'PENDING-08',
    title: 'Điều kiện cho phép của giáo viên đối với Mã 15 (Buôn bán đồ ăn)',
    ambiguity: 'Văn bản mục II.2 ghi "Tự ý đem đồ ăn thức uống... khi không có sự cho phép của giáo viên". Khi giáo viên cho phép (phục vụ bài học ngoại khóa/kế hoạch dạy học) thì không cấu thành vi phạm.',
    source_reference: 'QĐ 525 Mục II.2 mã 15',
    options: [
      { id: 'opt_v15_require_teacher_check', label: 'Bắt buộc xác nhận câu hỏi: "Giáo viên có cho phép buôn bán không?" trước khi lập vi phạm', description: 'Nếu Có thì không tạo mã V15' },
      { id: 'opt_v15_always_violation', label: 'Cấm tuyệt đối mọi hoạt động buôn bán', description: 'Không ngoại lệ' },
    ],
    selected_option: 'opt_v15_require_teacher_check',
    basis: 'Phê duyệt trực tiếp theo phương án đã chọn (GVCN & Ban Cán Sự Lớp 10A16)',
    effective_from: '2026-09-01',
    effective_to: '2027-06-30',
    status: 'confirmed_by_gvcn',
    configured_by: 'Thầy Trần Duy Tân (GVCN)',
    confirmed_by: 'Thầy Trần Duy Tân (GVCN)',
  },
  {
    code: 'PENDING-09',
    title: 'Diễn giải cú pháp văn bản gốc Mã 19 (Trốn tiết)',
    ambiguity: 'Văn bản gốc viết: "Trốn tiết giờ học, dự lễ, các buổi hoạt động ngoài giờ chính khóa". Cú pháp dễ gây hiểu lầm thành tham dự lễ cũng bị phạt.',
    source_reference: 'QĐ 525 Mục II.2 mã 19',
    options: [
      { id: 'opt_v19_truancy_all', label: 'Diễn giải: "Trốn tiết trong giờ học, trốn dự lễ, trốn các buổi hoạt động ngoài giờ"', description: 'Hành vi vi phạm là hành vi "trốn" (vắng mặt bất hợp pháp)' },
      { id: 'opt_v19_strict_hold', label: 'Giữ nguyên văn bản gốc, yêu cầu GVCN xác nhận từng trường hợp cụ thể', description: 'Không tự động xử phạt khi chưa rõ ý tứ' },
    ],
    selected_option: 'opt_v19_truancy_all',
    basis: 'Phê duyệt trực tiếp theo phương án đã chọn (GVCN & Ban Cán Sự Lớp 10A16)',
    effective_from: '2026-09-01',
    effective_to: '2027-06-30',
    status: 'confirmed_by_gvcn',
    configured_by: 'Thầy Trần Duy Tân (GVCN)',
    confirmed_by: 'Thầy Trần Duy Tân (GVCN)',
  },
];
